--Find Total Number of Customers by Countries

SELECT 
country,
count(customer_key) AS total_cutomers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_cutomers DESC

--Find total customers by gender
SELECT 
gender,
count(customer_key) AS total_cutomers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_cutomers DESC

--Find total products by category
SELECT
category,
COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC

--What is average costs in each category?
SELECT
category,
avg(cost) AS avg_cost
FROM gold.dim_products
GROUP BY category
ORDER BY avg_cost DESC

--What is the total revenue generated by each category

SELECT
p.category,
SUM(f.sales_amount) AS total_revenue
FROM
gold.fact_sales f
LEFT JOIN gold.dim_products p
ON f.product_key = p.product_key
GROUP BY p.category
order by total_revenue DESC

-- What is the total revenue generated by each customer?
SELECT
c.customer_key,
c.first_name,
c.last_name,
SUM(f.sales_amount) AS total_revenue
FROM
gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON f.customer_key = c.customer_key
GROUP BY 
c.customer_key,
c.first_name,
c.last_name
order by total_revenue DESC

--What is the distribution of items sold across countries?

SELECT
c.country,
SUM(f.quantity) AS total_sold_items
FROM
gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key
GROUP BY c.country
ORDER BY total_sold_items DESC

